InfraKit configuration files now named based on target AND plugin names. All infrakit configuration now in the Docker volume. Disable the certificate management service for now

diff --git a/bootstrap/bootstrap b/bootstrap/bootstrap
--- a/bootstrap/bootstrap
+++ b/bootstrap/bootstrap
@@ -10,10 +10,9 @@ INFRAKIT_DOCKER_IMAGE=appcelerator/infrakit-docker:1.0.0
 SSL_KEY_LENGTH=2048
 CERTIFICATE_SERVER_IMAGE=ndegory/certauth:latest
 CERT_DIR=~/.config/infrakit/certs
-LOCAL_CONFIG=~/.config/infrakit/infrakit
-INFRAKIT_OPTIONS="-e INFRAKIT_HOME=$INFRAKIT_HOME -v $LOCAL_CONFIG:$INFRAKIT_HOME"
-INFRAKIT_PLUGINS_OPTIONS="-v /var/run/docker.sock:/var/run/docker.sock -e INFRAKIT_PLUGINS_DIR=$INFRAKIT_HOME/plugins"
 BOOTSTRAP_VOLUME=amp-bootstrap
+INFRAKIT_OPTIONS="-e INFRAKIT_HOME=$INFRAKIT_HOME -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME"
+INFRAKIT_PLUGINS_OPTIONS="-v /var/run/docker.sock:/var/run/docker.sock -e INFRAKIT_PLUGINS_DIR=$INFRAKIT_HOME/plugins"
 BRIDGE_NETWORK=hostnet
 
 # check if the bootstrap script is executed inside a container
@@ -98,6 +97,48 @@ EOF
   fi
 }
 
+# prepare a Docker volume for the infrakit configuration
+# works even when the Docker host is not local (running from inside a container on the host)
+# args:
+#   - path of the directory containing the configuration
+# TODO: add a force option to remove the volume if it already exists, and add a hint when the volume exists and the option is not used
+_prepare_configuration_volume() {
+      local _d=$1
+      local _dockerfile
+      local _dockerimage
+      _dockerfile=$(mktemp $_d/ikt.vol.XXXXXX)
+      _dockerimage=$(basename $_dockerfile | tr '[:upper:]' '[:lower:]')
+      echo "preparing a Docker image with the configuration data"
+      cat >> $_dockerfile << EOF
+FROM alpine:3.5
+WORKDIR $INFRAKIT_HOME
+COPY . $INFRAKIT_HOME
+EOF
+      if [ -n "$envfile" ]; then
+        local _envfile=$(mktemp $_d/ikt.env.XXXXXX)
+        cp "$envfile" $_envfile
+        cat >> $_dockerfile << EOF
+COPY $(basename $_envfile) $INFRAKIT_HOME/env.ikt
+EOF
+      fi
+      cat >> $_dockerfile << EOF
+RUN mkdir -p $INFRAKIT_HOME/logs $INFRAKIT_HOME/plugins $INFRAKIT_HOME/configs
+VOLUME $INFRAKIT_HOME
+EOF
+      docker build -t $_dockerimage -f $_dockerfile $_d >/dev/null|| exit 1
+      rm "$_envfile"
+      docker volume inspect $BOOTSTRAP_VOLUME >/dev/null 2>&1
+      if [ $? -eq 0 ]; then
+        echo "The Docker volume $BOOTSTRAP_VOLUME already exists, a cluster is probably already running, abort" >&2
+        rm $_dockerfile
+        exit 1
+      fi
+      echo "creating Docker volume $BOOTSTRAP_VOLUME with the configuration data"
+      docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME $_dockerimage true
+      rm -f $_dockerfile
+      docker image rm $_dockerimage >/dev/null
+}
+
 # define and prepare the source directory
 _set_source() {
   local _d
@@ -105,11 +146,16 @@ _set_source() {
   InfraKitConfigurationBaseURL=$1
   # if a remote location is provided, the configuration will be searched there
   if $(echo "$InfraKitConfigurationBaseURL" | grep -q "://"); then
-    CONFIG_TPL=$InfraKitConfigurationBaseURL/config.$provider.tpl
-    PLUGINS_CFG=$InfraKitConfigurationBaseURL/plugins.json
-    CONTAINER_CONFIG_TPL=$CONFIG_TPL
-    CONTAINER_PLUGINS_CFG=$PLUGINS_CFG
+    CONTAINER_CONFIG_TPL=$InfraKitConfigurationBaseURL/config.${provider}-${target}.tpl
+    CONTAINER_PLUGINS_CFG=$InfraKitConfigurationBaseURL/plugins.json
+    # a new random temporary directory used as the source
+    _d=$(mktemp -d)
+    if [ "x$provider" = "xterraform" ]; then
+      curl $InfraKitConfigurationBaseURL/terraform 
+    fi
   else
+    CONTAINER_CONFIG_TPL=file://$INFRAKIT_HOME/config.${provider}-${target}.tpl
+    CONTAINER_PLUGINS_CFG=file://$INFRAKIT_HOME/plugins.json
     # the provided path, or just use the local directory as the source
     _d=${InfraKitConfigurationBaseURL:-$0}
     which realpath >/dev/null 2>&1
@@ -119,53 +165,8 @@ _set_source() {
     if [ ! -d $_d ]; then
       _d=$(dirname $_d)
     fi
-    echo -n "copying source files from $_d to $LOCAL_CONFIG"
-    # if this script runs outside of a container, we just copy the file next to it to the LOCAL_CONFIG folder
-    # else, it should be copied by the docker daemon, so we should run a container mounting the files and copying
-    #       it on the Docker host, because LOCAL_CONFIG will be used by containers
-    if $(_am_i_in_a_container); then
-      echo " from inside a container"
-      local _dockerfile
-      local _dockerimage
-      _dockerfile=$(mktemp $_d/ikt.vol.XXXXXX)
-      _dockerimage=$(basename $_dockerfile | tr '[:upper:]' '[:lower:]')
-      LOCAL_CONFIG=$INFRAKIT_HOME
-      # to send the configuration in the Docker host context, we have to build an image
-      echo "preparing a Docker image with the configuration data"
-      cat >> $_dockerfile << EOF
-FROM alpine:3.5
-WORKDIR $INFRAKIT_HOME
-COPY . $INFRAKIT_HOME
-RUN mkdir -p $INFRAKIT_HOME/logs $INFRAKIT_HOME/plugins $INFRAKIT_HOME/configs
-VOLUME $INFRAKIT_HOME
-EOF
-      docker build -t $_dockerimage -f $_dockerfile $_d >/dev/null|| exit 1
-      docker volume inspect $BOOTSTRAP_VOLUME >/dev/null 2>&1
-      if [ $? -eq 0 ]; then
-        echo "The Docker volume $BOOTSTRAP_VOLUME already exists, a cluster is probably already running, abort" >&2
-        exit 1
-      fi
-      echo "creating Docker volume $BOOTSTRAP_VOLUME with the configuration data"
-      docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME $_dockerimage true
-      rm -f $_dockerfile
-      docker image rm $_dockerimage >/dev/null
-      # from now the container shouldn't mount the host LOCAL_CONFIG to /infrakit
-      # but the named volume instead
-      INFRAKIT_OPTIONS="-e INFRAKIT_HOME=$INFRAKIT_HOME -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME"
-    else
-      echo " on the host, you may want to clean up $LOCAL_CONFIG afterwards"
-      mkdir -p $LOCAL_CONFIG || exit 1
-      cp $_d/bootstrap* $_d/*.sh $_d/*.tpl $_d/plugins.json $_d/*.ikt $LOCAL_CONFIG/ || exit 1
-      if [ "x$provider" = "xterraform" ] && [ -d $_d/terraform ]; then
-        cp -pr $_d/terraform $LOCAL_CONFIG || exit 1
-      fi
-      mkdir -p $LOCAL_CONFIG/logs $LOCAL_CONFIG/plugins $LOCAL_CONFIG/configs || exit 1
-    fi
-    CONFIG_TPL=file://$LOCAL_CONFIG/config.$provider.tpl
-    PLUGINS_CFG=file://$LOCAL_CONFIG/plugins.json
-    CONTAINER_CONFIG_TPL=file://$INFRAKIT_HOME/config.$provider.tpl
-    CONTAINER_PLUGINS_CFG=file://$INFRAKIT_HOME/plugins.json
   fi
+  _prepare_configuration_volume $_d
 }
 
 # sets the number of managers and workers
@@ -183,52 +184,54 @@ _set_size() {
   echo "the $_size nodes will be distributed as $_manager_size managers and $_worker_size workers"
   _vars="{{ global \"/swarm/size/manager\" \"$_manager_size\" }}
 {{ global \"/swarm/size/worker\" \"$_worker_size\" }}"
-  if $(_am_i_in_a_container); then
-    docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "echo '$_vars' >> $INFRAKIT_HOME/env.ikt" || exit 1
-  else
-    echo $_vars >> $LOCAL_CONFIG/env.ikt
+  docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "echo '$_vars' >> $INFRAKIT_HOME/env.ikt" || exit 1
+  echo "cluster size added to $INFRAKIT_HOME/env.ikt"
+}
+
+# get the private IP
+# first with the AWS metadata service, and then a more standard way
+_get_ip() {
+  local _ip
+  _ip=$(curl -m 3 169.254.169.254/latest/meta-data/local-ipv4 2>/dev/null) || _ip=$(ip a show dev eth0 2>/dev/null | grep inet | grep eth0 | tail -1 | sed -e 's/^.*inet.//g' -e 's/\/.*$//g')
+  if [ -z "$_ip" ];then
+    _ip=$(ifconfig $(netstat -nr | awk 'NF==6 && $1 ~/default/ {print $6}' | tail -1) | awk '$1 == "inet" {print $2}')
   fi
-  echo "cluster size added to $LOCAL_CONFIG/env.ikt"
+  if [ -z "$_ip" ];then
+    echo "unable to guess the private IP" >&2
+    exit 1
+  fi
+  echo $_ip
 }
 
 # run a certificate signing service
 _run_certificate_service() {
-  echo "warning: the certificate service is not production ready, use it only for development purposes" >&2
   local IP
-  # get the local private IP, first with the AWS metadata service, and then a more standard way
-  IP=$(curl -m 3 169.254.169.254/latest/meta-data/local-ipv4 2>/dev/null) || IP=$(ip a show dev eth0 2>/dev/null | grep inet | grep eth0 | tail -1 | sed -e 's/^.*inet.//g' -e 's/\/.*$//g')
-  if [ -z "$IP" ];then
-    IP=$(ifconfig $(netstat -nr | awk 'NF==6 && $1 ~/default/ {print $6}' | tail -1) | awk '$1 == "inet" {print $2}')
-  fi
-  if [ -z "$IP" ];then
-    echo "unable to guess the private IP" >&2
-    exit 1
-  fi
-
-  cad=$(mktemp -d)
-  if [ $? -ne 0 ] || [ -z "$cad" ]; then
-    echo "unable to create a temporary directory to build the certificate management" >&2
-    exit 1
-  fi
-  echo "build a certificate management service (in $cad)..."
-  pushd $cad
-  git clone https://github.com/ndegory/certificate.authority.git
-  pushd certificate.authority 2>/dev/null
-  docker build -t $CERTIFICATE_SERVER_IMAGE . || exit 1
-  popd -1 2>/dev/null && popd 2>/dev/null
-  rm -rf $cad
-  echo "temporary directory has been removed"
+  IP=$(_get_ip)
   docker container ls --format '{{.Names}}' | grep -qw certauth
-  if [ $? -ne 0 ]; then
+  if [ $? -eq 0 ]; then
+    echo "the certificate management service is already running"
+  else
+    echo "warning: the certificate service is not production ready, use it only for development purposes" >&2
+    cad=$(mktemp -d)
+    if [ $? -ne 0 ] || [ -z "$cad" ]; then
+      echo "unable to create a temporary directory to build the certificate management" >&2
+      exit 1
+    fi
+    echo "build a certificate management service (in $cad)..."
+    pushd $cad
+    git clone https://github.com/ndegory/certificate.authority.git
+    pushd certificate.authority 2>/dev/null
+    docker build -t $CERTIFICATE_SERVER_IMAGE . || exit 1
+    popd -1 2>/dev/null && popd 2>/dev/null
+    rm -rf $cad
+    echo "temporary directory has been removed"
     echo "run the certificate management service..."
     docker run -d --restart always -p 80 --name certauth $CERTIFICATE_SERVER_IMAGE || exit 1
-  else
-    echo "the certificate management service is already running"
   fi
   CERTIFICATE_SERVER_PORT=$(docker inspect certauth --format='{{(index (index .NetworkSettings.Ports "80/tcp") 0).HostPort}}')
   echo "certificate server listening on port $CERTIFICATE_SERVER_PORT"
-  echo "{{ global \"/certificate/ca/service\" \"$IP:$CERTIFICATE_SERVER_PORT\" }}" >> $LOCAL_CONFIG/env.ikt
-  # TODO: in a container env.ikt change
+  _vars="{{ global \"/certificate/ca/service\" \"$IP:$CERTIFICATE_SERVER_PORT\" }}"
+  docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "echo '$_vars' >> $INFRAKIT_HOME/env.ikt" || exit 1
 }
 
 # generate a certificate for the Docker client
@@ -240,11 +243,11 @@ _get_client_certificate() {
   if [ ! -f $CERT_DIR/ca.pem ]; then
     echo "generating a self-signed CA..."
     # (used by the Swarm flavor plugin)
-    curl localhost:$CERTIFICATE_SERVER_PORT/ca > $CERT_DIR/ca.pem
+    curl http://localhost:$CERTIFICATE_SERVER_PORT/ca > $CERT_DIR/ca.pem
     echo "generating a certificate for the Docker client in $CERT_DIR..."
     openssl genrsa -out $CERT_DIR/client-key.pem $SSL_KEY_LENGTH
     openssl req -subj '/CN=client' -new -key $CERT_DIR/client-key.pem -out $CERT_DIR/client.csr
-    curl --data "csr=$(cat $CERT_DIR/client.csr | sed 's/+/%2B/g');ext=extendedKeyUsage=clientAuth" localhost:$CERTIFICATE_SERVER_PORT/csr > $CERT_DIR/client.pem
+    curl --data "csr=$(cat $CERT_DIR/client.csr | sed 's/+/%2B/g');ext=extendedKeyUsage=clientAuth" http://localhost:$CERTIFICATE_SERVER_PORT/csr > $CERT_DIR/client.pem
     ls -l $CERT_DIR/client.pem
     rm -f $CERT_DIR/client.csr
   fi
@@ -255,18 +258,10 @@ _get_client_certificate() {
 _run_ikt_container() {
   local _should_wait_for_plugins=0
   local _infrakit_image
-  if $(_am_i_in_a_container); then
-    docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "echo 'group' >> $INFRAKIT_HOME/leader" || exit 1
-  else
-    echo "group" > $LOCAL_CONFIG/leader
-  fi
+  docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "echo 'group' >> $INFRAKIT_HOME/leader" || exit 1
 
   # remove old customized configuration just in case
-  if $(_am_i_in_a_container); then
-    docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "sed -i.bak 's/^{{ global \"\/script\/baseurl\"/#{{ global \"\/script\/baseurl\"/' $INFRAKIT_HOME/env.ikt" || exit 1
-  else
-    sed -i.bak 's/^{{ global "\/script\/baseurl"/#{{ global "\/script\/baseurl"/' $LOCAL_CONFIG/env.ikt
-  fi
+  docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "sed -i.bak 's/^{{ global \"\/script\/baseurl\".\*$//' $INFRAKIT_HOME/env.ikt" || exit 1
   local _extra_plugins=""
   # managed plugins should be started in the main infrakit container
   echo "$MANAGED_PLUGINS" | grep -qw $provider
@@ -276,10 +271,24 @@ _run_ikt_container() {
   docker container ls --format '{{.Names}}' | grep -qw infrakit
   if [ $? -ne 0 ]; then
     # cleanup
-    if $(_am_i_in_a_container); then
-      docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "rm -f $LOCAL_CONFIG/plugins/flavor-* $LOCAL_CONFIG/plugins/group* $LOCAL_CONFIG/plugins/instance-*" || exit 1
-    else
-      rm -f $LOCAL_CONFIG/plugins/flavor-* $LOCAL_CONFIG/plugins/group* $LOCAL_CONFIG/plugins/instance-*
+    docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "rm -f $INFRAKIT_HOME/plugins/flavor-* $INFRAKIT_HOME/plugins/group* $INFRAKIT_HOME/plugins/instance-*" || exit 1
+    # set a stackname if it's not already set. Useful when deploying on AWS
+    docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "grep -q /aws/stackname $INFRAKIT_HOME/env.ikt"
+    if [ $? -ne 0 ]; then
+      local _stackname
+      _stackname=$(uuidgen | tr '[:upper:]' '[:lower:]')
+      if [ $? -ne 0 ]; then
+        # fall back to the hostname if uuidgen is not available
+        _stackname=$(hostname)
+      fi
+      docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "echo '{{ global \"/aws/stackname\" \"$_stackname\" }}' >> $INFRAKIT_HOME/env.ikt" || exit 1
+    fi
+    # set the provisioner IP if not already set. Useful when bootstraping with the first manager
+    docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "grep -q /bootstrap/ip $INFRAKIT_HOME/env.ikt"
+    if [ $? -ne 0 ]; then
+      local _ip
+      _ip=$(_get_ip)
+      docker run --rm -v $BOOTSTRAP_VOLUME:$INFRAKIT_HOME alpine:3.5 sh -c "echo '{{ global \"/bootstrap/ip\" \"$_ip\" }}' >> $INFRAKIT_HOME/env.ikt" || exit 1
     fi
     if [ "x$provider" = "xdocker" ]; then
         echo "making sure the network $BRIDGE_NETWORK is created"
@@ -319,7 +328,8 @@ _run_ikt_plugin_container() {
       docker container ls --format '{{.Names}}' | grep -qw instance-plugin-$_plugin
       if [ $? -ne 0 ]; then
         # first, cleanup the pid and socket files
-        rm -f $LOCAL_CONFIG/plugins/instance-${_plugin}*
+        # TODO: container way
+        rm -f $INFRAKIT_HOME/plugins/instance-${_plugin}*
         _image=$(eval echo \${INFRAKIT_$(echo $_plugin | tr '[:lower:]' '[:upper:]')_IMAGE})
         if [ -z "$_image" ]; then
             echo "no image defined for plugin $_plugin"
@@ -375,29 +385,15 @@ _kill_plugins() {
 
 # removes the configuration files
 _clean_config() {
-  if [ -f $LOCAL_CONFIG/config.json ]; then
-    rm -f $LOCAL_CONFIG/config.json
-    echo "config.json has been removed"
-  fi
-  if [ -f $LOCAL_CONFIG/env.ikt ]; then
-    rm -f $LOCAL_CONFIG/env.ikt
-    echo "env.ikt has been removed"
-  fi
-  if [ -d $LOCAL_CONFIG/configs ]; then
-    rm -rf $LOCAL_CONFIG/configs
-    echo "configs folder has been removed"
-  fi
   if [ -d $CERT_DIR ]; then
     rm -f $CERT_DIR/ca.pem $CERT_DIR/client.pem $CERT_DIR/client-key.pem
     echo "client certificates have been removed"
   fi
-  if $(_am_i_in_a_container); then
-    docker volume inspect $BOOTSTRAP_VOLUME >/dev/null 2>&1
-    if [ $? -eq 0 ]; then
-      docker volume rm $BOOTSTRAP_VOLUME >/dev/null 2>&1 && echo "configuration volume deleted"
-    else
-      echo "no configuration volume to delete"
-    fi
+  docker volume inspect $BOOTSTRAP_VOLUME >/dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    docker volume rm $BOOTSTRAP_VOLUME >/dev/null 2>&1 && echo "configuration volume deleted"
+  else
+    echo "no configuration volume to delete"
   fi
 }
 
@@ -406,16 +402,13 @@ _prepare_config_container() {
   echo "prepare the InfraKit configuration file..."
   local _config=$(mktemp)
   docker exec infrakit infrakit template --log 5 --url $CONTAINER_CONFIG_TPL > $_config
-  if $(_am_i_in_a_container); then
-    docker cp $_config infrakit:$INFRAKIT_HOME/config.json || exit 1
-    rm $_config
-  else
-    mv $_config $LOCAL_CONFIG/config.json
-  fi
+  docker cp $_config infrakit:$INFRAKIT_HOME/config.json || exit 1
   if [ $? -ne 0 ]; then
     echo "failed, template URL was $CONTAINER_CONFIG_TPL" >&2
+    rm $_config
     exit 1
   fi
+  rm $_config
 }
 
 # deploy the infrakit configuration
@@ -433,22 +426,33 @@ _run_registry() {
              registry:2
 }
 
+# where to deploy
+VALID_TARGETS="aws local"
+# Infrakit plugins used for deployment
 VALID_PROVIDERS="aws docker terraform"
 # we can't run InfraKit in a container for these plugins
 NON_CONTAINERIZED_PLUGINS=""
 # providers managed by infrakit (integrated plugin)
 MANAGED_PLUGINS="terraform"
+target=local
 provider=docker
+envfile=""
 should_pull=1
 clustersize=5
 clean=0
-while getopts ":p:n:hfc" opt; do
+while getopts ":t:p:e:n:hfc" opt; do
   case $opt in
   n)
       clustersize=$OPTARG
       ;;
+  t)
+      echo "$VALID_TARGETS" | grep -wq "$OPTARG" && target=$OPTARG
+      if [ -z "$target" ]; then
+          echo "valid targets are $VALID_TARGETS"
+          exit 1
+      fi
+      ;;
   p)
-      provider=""
       echo "$VALID_PROVIDERS" | grep -wq "$OPTARG" && provider=$OPTARG
       if [ -z "$provider" ]; then
           echo "valid providers are $VALID_PROVIDERS"
@@ -456,7 +460,7 @@ while getopts ":p:n:hfc" opt; do
       fi
       ;;
   h)
-      echo "usage: $(basename $0) [-p provider] [-n cluster size] [-f] [-h]"
+      echo "usage: $(basename $0) [-t target] [-p provider] [-n cluster size] [-f] [-h]"
       exit 0
       ;;
   f)
@@ -465,6 +469,13 @@ while getopts ":p:n:hfc" opt; do
       ;;
   c)
       clean=1
+      ;;
+  e)
+      envfile=$OPTARG
+      if [ ! -f "$envfile" ]; then
+        echo "$envfile does not exist" >&2
+        exit 1
+      fi
       ;;
   \?)
       echo "invalid option: -$OPTARG" >&2
@@ -478,6 +489,11 @@ while getopts ":p:n:hfc" opt; do
 done
 shift "$((OPTIND-1))"
 
+# in case only the provider has been set, and it's not docker, use the target name as provider
+if [ "x$target" = "xlocal" ] && [ "x$provider" != "xdocker" ]; then
+    target=$provider
+fi
+
 if [ $clean -eq 1 ]; then
   _destroy_groups
   _kill_plugins
@@ -487,7 +503,7 @@ if [ $clean -eq 1 ]; then
 fi
 _set_source $1
 _set_size $clustersize
-if [ "$provider" != "docker" ]; then _run_certificate_service; _get_client_certificate; fi
+#if [ "$provider" != "docker" ]; then _run_certificate_service; _get_client_certificate; fi
 if [ "$provider" = "docker" ]; then _run_registry; fi
 if [ $should_pull -eq 1 ]; then _pull_images $provider; fi
 _run_ikt_container $provider
