update version test

diff --git a/platform/tests/version b/platform/tests/version
--- a/platform/tests/version
+++ b/platform/tests/version
@@ -5,12 +5,19 @@ result=$(amp -s localhost version)
 echo $result
 
 # not finding the version is an error
-version="v[0..9]{1,2}\.[0..9]{1,3}\.[0..9]{1,3}"
+version="v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"
 echo $result | grep -E "Version:[[:space:]]+$version"
-[[ $? -ne 0 ]] && ((ec++)) && >&2 echo "error: missing version"
+if [[ $? -ne 0 ]]; then
+	((ec++))
+	echo "error: missing version"
+fi
 
 # finding "not connected" is an error
 echo $result | grep "not connected"
-[[ $? -eq 0 ]] && ((ec++)) && >&2 echo "error: not connected"
+if [[ $? -eq 0 ]]; then
+	((ec++))
+	echo "error: not connected"
+fi
 
 exit $ec
+
