modify build order, services, increase service check timeout

diff --git a/hack/deploy b/hack/deploy
--- a/hack/deploy
+++ b/hack/deploy
@@ -20,7 +20,8 @@ checkexit() {
 }
 
 cleanup() {
-  [[ SUCCESS -ne 1 && ! -z $CID ]] && echo "clean up" && $bootstrap -d $CID
+#  [[ SUCCESS -ne 1 && ! -z $CID ]] && echo "clean up" && $bootstrap -d $CID
+exit 0
 }
 trap cleanup EXIT
 
@@ -79,12 +80,19 @@ pushimage localhost:5000 appcelerator/amplifier:local
 pushimage localhost:5000 appcelerator/ampbeat:local
 pushimage localhost:5000 appcelerator/agent:local
 
-echo "deploy stacks to cluster"
+echo "deploy amplifier stack to cluster"
 deploystack amplifier.stack.yml amplifier
+
+echo "wait for all amplifier stack service replicas to be running"
+$servicescheck 600
+checkexit $? "service replica checks timed out"
+ok
+
+echo "deploy monitoring stack to cluster"
 deploystack monitoring.stack.yml monitoring
 
-echo "wait for all services replicas to be running"
-$servicescheck 300
+echo "wait for all monitoring stack service replicas to be running"
+$servicescheck 600
 checkexit $? "service replica checks timed out"
 ok
 
