deployment with CLI on manager node of a (BYO) swarm

diff --git a/platform/bin/deploy b/platform/bin/deploy
--- a/platform/bin/deploy
+++ b/platform/bin/deploy
@@ -46,6 +46,7 @@ cluster_create() {
   local _label
   local _label_prefix="amp.type."
   local _labels="mq kv search api metrics route core user"
+  local _current_labels
   _target="$(deployment_target)"
   case $_target in
   local) # for local, enable swarm mode if not already enabled and create the ampnet overlay network
@@ -70,7 +71,11 @@ cluster_create() {
       echo "overlay network ampnet found" >&2
     fi
     # add all service labels for orchestration
+    _current_labels=$(for n in $(docker node ls -q); do docker node inspect $n --pretty | grep amp.type | sed -e 's/.*\(amp.type.*\) *=.*$/\1/'; done | sort | uniq)
     for _label in $_labels; do
+      echo $_current_labels | grep -q "${_label_prefix}${_label}" && continue
+      echo "adding missing label $_label_prefix$_label" >&2
+      echo "you may want to redistribute the labels to match your service scheduling expectations" >&2
       docker node update --label-add "${_label_prefix}${_label}=true" "$_clusterid" >/dev/null
     done
     echo $_clusterid
@@ -140,7 +145,8 @@ cluster_nodecount() {
   _target=$(deployment_target)
   case $_target in
   local) # single manager node
-    echo 1
+    docker node ls -q | wc -w
+    return 0
     ;;
   dind|aws)
     _count=$(bootstrap -t $_target -l $_clusterid | wc -l)
@@ -167,6 +173,7 @@ cluster_workercount() {
   case $_target in
   local) # single manager node
     echo 0
+    return 0
     ;;
   dind|aws)
     _count=$(bootstrap -t $_target -l $_clusterid | grep -c worker)
@@ -200,6 +207,7 @@ EOF
   rm -rf $builddir
   docker run --rm -v amp-stacks:/stacks $image
   docker image rm $image > /dev/null
+  echo "+ volume amp-stacks" >&2
 }
 
 # creates a amp-secrets volume by sending the local secrets to the host in a build context
@@ -219,6 +227,7 @@ EOF
   rm -rf $builddir
   docker run --rm -v amp-secrets:/secrets $image
   docker image rm $image > /dev/null
+  echo "+ volume amp-secrets" >&2
 }
 
 # sets hosts for Docker remote API and for the Docker registry
@@ -231,6 +240,16 @@ set_deployment_variables(){
     secrets_path="$SECRETSDIR"
     amps="docker"
     domainname=$localdomainname
+    if [[ -z "$MANAGER_HOST" && $(docker node ls -q | wc -w) -gt 1 ]]; then
+      # not a single node, so we're setting the env variable for prometheus access
+      # to a manager engine API, assumption is that the CLI is run on a manager 
+      # first try the AWS metadata service
+      MANAGER_HOST=$(curl -m 3 -f 169.254.169.254/latest/meta-data/local-ipv4 2>/dev/null) || MANAGER_HOST=$(ip a show dev eth0 2>/dev/null | grep inet | grep eth0 | tail -1 | sed -e 's/^.*inet.//g' -e 's/\/.*$//g')
+      # else get the IP from the host. Won't work from inside a container
+      [[ -z "$MANAGER_HOST" ]] && MANAGER_HOST=$(ifconfig $(netstat -nr | awk 'NF>4 && $1 ~/(default)|(0.0.0.0)/ {print $NF}' | tail -1) | awk '$1 == "inet" {print $2}' | grep -v "127.0.0.1" | sed -e 's/addr://')
+      echo "setting MANAGER_HOST prometheus variable to $MANAGER_HOST" >&2
+      export MANAGER_HOST
+    fi
     return
     ;;
   dind)
@@ -325,7 +344,6 @@ kurl() {
 }
 
 # pushes the amplifier configuration in a secret
-# TODO: empty for now
 prepare_amplifier_configuration(){
   local _conf
   local cid
@@ -333,13 +351,14 @@ prepare_amplifier_configuration(){
   _conf="$SECRETSDIR/amplifier.yml"
   if [[ ! -f "$_conf" ]]; then
     local supasswd
+    echo "creating a default configuration for amplifier_yml" >&2
     mkdir -p "$SECRETSDIR"
-    echo "JWTSecretKey: "$(docker run --rm alpine sh -c '< /dev/urandom tr -dc [:alnum:] | head -c${1:-128}') > "$_conf"
-    supasswd=$(docker run --rm alpine sh -c '< /dev/urandom tr -dc [:alnum:] | head -c${1:-32}')
+    echo "JWTSecretKey: "$(docker run --rm alpine:3.5 sh -c '< /dev/urandom tr -dc [:alnum:] | head -c${1:-128}') > "$_conf"
+    supasswd=$(docker run --rm alpine:3.5 sh -c '< /dev/urandom tr -dc [:alnum:] | head -c${1:-32}')
     echo "SUPassword: " "$supasswd" >> "$_conf"
-    echo "The super user password for this deployment is: $supasswd"
+    echo "The super user password for this deployment is: $supasswd" >&2
   else
-    echo "using existing configuration for the amplifier_yml secret" >&2
+    echo "using provided configuration for the amplifier_yml secret" >&2
   fi
   # copy the configuration in the amp-secrets volume
   cid=$(docker run -d --rm -v amp-secrets:/secrets alpine:3.5 sleep 15)
@@ -357,8 +376,9 @@ prepare_prometheus_configuration(){
   if [[ ! -f "$_conf" ]]; then
     mkdir -p "$SECRETSDIR"
     echo > "$_conf"
+    echo "creating an empty configuration for prometheus_alerts_rules" >&2
   else
-    echo "using existing configuration for the prometheus_alerts_rules secret" >&2
+    echo "using provided configuration for the prometheus_alerts_rules secret" >&2
   fi
   # copy the configuration in the amp-secrets volume
   cid=$(docker run -d --rm -v amp-secrets:/secrets alpine:3.5 sleep 15)
@@ -375,6 +395,7 @@ prepare_alertmanager_configuration(){
   _conf="$SECRETSDIR/alertmanager.yml"
   if [[ ! -f "$_conf" ]]; then
     mkdir -p "$SECRETSDIR"
+    echo "creating a default configuration for alertmanager_yml" >&2
     cat > "$_conf" << EOF
 global:
   smtp_smarthost: 'localhost:25'
@@ -387,7 +408,7 @@ receivers:
   - to: 'null@localhost'
 EOF
   else
-    echo "using existing configuration for the alertmanager_yml secret" >&2
+    echo "using provided configuration for the alertmanager_yml secret" >&2
   fi
   # copy the configuration in the amp-secrets volume
   cid=$(docker run -d --rm -v amp-secrets:/secrets alpine:3.5 sleep 15)
@@ -424,15 +445,17 @@ prepare_certificates() {
   if [[ $? -ne 0 || -z "$cid" ]]; then return 1; fi
   docker cp "$certfile" $cid:/secrets/$name.pem
   docker kill "$cid" >/dev/null 2>&1
-  echo "creating the certificate secret"
   $amps secret create "certificate_atomiq" "$secrets_path/$name.pem" >/dev/null && echo "secret certificate_atomiq successfully created" >&2
+  code=$?
+  [[ $rm_certfile -eq 1 ]] && rm -f "$certfile"
+  return $code
 }
 
 # process the command line options and arguments
 parse_cmd() {
-  while getopts ":w:m:t:l:T:c:r:n:p:g:dsD:" opt; do
+  while getopts ":w:m:t:l:T:cr:n:p:g:dsD:" opt; do
     case $opt in
-    w|m|t|l) # just pass it to the bootstrap script
+    w|m|l) # just pass it to the bootstrap script
       BOOTSTRAP_OPTIONS="$BOOTSTRAP_OPTIONS -${opt} $OPTARG"
       ;;
     s) STATUS=1
@@ -472,6 +495,9 @@ parse_cmd() {
       ;;
     c)
       CHECK=1
+      ;;
+    t) # target
+      deployment_target $OPTARG >/dev/null
       ;;
     p) # provider
       deployment_target $OPTARG >/dev/null
@@ -538,11 +564,6 @@ bootstrap_cluster() {
 deploy_stacks() {
   local maxwait=300 # should be less than 10 minutes (600s) so not to exceed travis deadline
   local _workercount
-
-  if [[ "$(deployment_target)" = "local" ]]; then
-    # force all placement constraints to deploy to a single manager
-    export NODE_ROLE=manager
-  fi
 
   echo "deploy amp monitoring stack to cluster - stage 1"
   _workercount=$(cluster_workercount $CID) || return 1
